# Generated by Django 3.2.4 on 2021-07-24 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ready', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('secret', models.CharField(default=uuid.uuid1, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BinaryField(db_index=True, max_length=16)),
                ('text', models.CharField(max_length=256)),
                ('collections', models.ManyToManyField(to='table.CardCollection')),
            ],
        ),
        migrations.CreateModel(
            name='BlackCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BinaryField(db_index=True, max_length=16)),
                ('text', models.CharField(max_length=1024)),
                ('card_plays', models.IntegerField()),
                ('collections', models.ManyToManyField(to='table.CardCollection')),
            ],
        ),
    ]
